ignore:
  - index.md
nav:
  - control-pilot.md
  - proximity-pilot.md
  - socket-lock.md
  - residual-current-monitor.md
  - energy-metering.md
  - CP-calibration.md
  - esp32s2-evse-d-a.md
  - "*"
  - build-examples.md
  - hmi-examples.md
